version: "3"
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
          DB_NAME: swagger_tutorial
          DB_USER: root
          DB_PASS: password
          DB_HOST: mysql
          DB_PORT: 3306
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle
      - bundle:/app/.bundle
      - node_modules:/app/node_modules
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
          - default
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  swagger:
    image: swaggerapi/swagger-editor
    ports:
      - '80:8080'
volumes:
  mysql-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local